---
# tasks file for webserver
- name: install nginx
  apt:
   name: nginx
   state: present

- name: Download Files from githiubcheg
  become: yes
  git:
     repo: https://github.com/Lord3D/homeworks.git
     dest: /tmp/temporata/


- name: copy index.html
  copy: src=/tmp/temporata/ansible/AnsRoles/roles/webserver/files/index.html dest={{ dest_folder }}/index.html mode=0555
  notify:
   - restart nginx



