---
  - name: Install and Launch the Simple NodeJS Application
    hosts: all
    tasks:

       - name: Download the NodeJS code from the GitRepo
         become: yes
         git:
            repo: https://github.com/Lord3D/homeworks/tree/master/ansible/AnsRoles/roles/webserver/files.git
            dest: /tmp/temporata/
